apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tlpk8a4mu-java-springboot
  janus-idp.io/tekton: tlpk8a4mu-java-springboot
  backstage.io/kubernetes-id: tlpk8a4mu-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tlpk8a4mu-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
